---

- hosts: altschool
  become: yes
  tasks:


  - name: update new server
    apt:
     upgrade: dist

  - name: install apache
    apt:
     name: apache2
     state: latest

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest

  - name: change timezone from UTC to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent

  - name: copy index.php file to server
    copy:
      src: index.php
      dest: /var/www/html
      owner: root
      group: root
      mode: 0644
